### ISSUE TITLE
Trouble loading Staubli driver fork

### ISSUE THREAD

**Issue by JGittles** [FAU-FAPS/adaptive_motion_control#1]
Hi all,

I have been having trouble loading in the Staubli driver fork in SRS, specifically I am not able to load the ros-server application. In reading the discussion around the PR upstream there is mention of velocity or motion addons that are required. Where can I find these if they are not already in-built to this repo or is there another area I should investigate? 

Thanks!

**Comment by enginkarlidag** [comment]
Hi Jordan,

it seems that I hadn't the notifications enabled so I missed your question here... I add here my answer from my email in case someone has the same problem.

Our [fork of the staubli_val3_driver](https://github.com/FAU-FAPS/staubli_val3_driver/tree/faps-devel) (faps-devel branch) uses some VAL3 functions that are only available if a certain addon is installed. These are not provided online as far as I know. You should contact Staubli for that.

You will need the "motion" addon for full functionality of the driver. It contains the velocity functions *and* the $getJntSpeedCmd function. The latter is used to get the joint velocities in the feedback message here:

https://github.com/FAU-FAPS/staubli_val3_driver/blob/8b4c7e3e469e9fab030195b48376da842b181600/staubli_val3_driver/val3/ros_server/dataStreamer.pgx#L34

If you only have the "velocity" addon you can use the velocity commands but not the joint-speed command! However, the code would then have to be adjusted manually.

Our fork is supposed to be merged upstream. Then the usage of the addons should probably be optional and also better documented. You can find the ongoing pull request here:

https://github.com/ros-industrial/staubli_val3_driver/pull/36
